### ISSUE TITLE
Create OSM NSD file generator 

### ISSUE THREAD

**Issue by qarawlus** [CN-UPB/tng-sdk-benchmark#22]
Handle existing NSD files and add the probe connection points to the NSD. 

Example from PED file: 
```
 - function: "mp.input"
        # loop longer than experiment lasts
        cmd_start: ["tcpreplay -i data -tK --loop 1000 --preload-pcap /pcaps/smallFlows.pcap"]
        cmd_stop: "./stop.sh"
        # cpu_bw: null  # float: fraction of CPU time in vim-emu (In OSM no need for this)
        cpu_cores: 1  # string: this is "cpuset_cpu" in vim-emu e.g. ["0, 1"] -> 2 CPUs
        mem_max: 1024  # int: Memory in MByte
        # mem_swap_max: null
        # io_bw: null
      - function: "mp.output"
        cmd_start: null
        cmd_stop: "./stop.sh"  # dump packet counters to logs
        # cpu_bw: null  # float: fraction of CPU time in vim-emu (In Openstack no need for this)
        cpu_cores: 1  # string: this is "cpuset_cpu" in vim-emu e.g. ["0, 1"] -> 2 CPUs
        mem_max: 1024  # int: Memory in MByte
        # mem_swap_max: null
        # io_bw: null
```

This would require that a probe is added to the input of the NSD (i.e. before the first VNF) and a probe to be added to the end of the NSD. 

```
constituent-vnfd:
        -   vnfd-id-ref: hackfest-simplecharm-vnf
            member-vnf-index: '1'
        -   vnfd-id-ref: hackfest-simplecharm-vnf
            member-vnf-index: '2'
```

**DEADLINE: Mon. 14.10.2019 - 08:00**

**Comment by avimehenwal** [comment]
Try 1 - Adding probes

![Screenshot_20191018_014318](https://user-images.githubusercontent.com/3624059/67142976-e095a400-f266-11e9-9449-3dd73d15a398.png)

**Comment by avimehenwal** [comment]
# TASKS
@avimehenwal 

- [X] Use a simple ubuntu to prototype probe
- [X] Test standalone script which attached probes to nsd
- [ ] Move your examples descriptor files to `tng-sdk-benchmark/examples-osm/services/`
- [ ] Reference From `sample-ns-3vnf`
- [ ] Make it work with code

**Comment by avimehenwal** [comment]
Agreed NSD with probes setup

![Screenshot_20191019_125931](https://user-images.githubusercontent.com/3624059/67143908-dd9fb100-f270-11e9-90a5-92e3d081318b.png)

**Comment by avimehenwal** [comment]
# TASKS ASSIGNMENT
@avimehenwal 

- [X] Use a simple ubuntu to prototype probe
- [X] Test standalone script which attached probes to nsd
- [x] Move your examples descriptor files to `tng-sdk-benchmark/examples-osm/services/`
- [x] Reference From `sample-ns-3vnf`
- [ ] Make it work with code

@Harshita-Puri @SuganthiJagan 

- [x] Write descriptor for probe using ubuntu image with 2 interfaces
- [x] Try to integrate nds_gen with existing haydar's code
